services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/${KDA_SAIL_IMAGE}
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - target: 80 
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            VIRTUAL_HOST: ${KDA_FQDN}
            COMPOSER: ${COMPOSER}
        volumes:
            - type: bind
              source: ./composer
              target: /home/sail/.config/composer
            - type: bind
              source: ../..
              read_only: true
              target: /var/www/monorepo
            - type: bind
              source: ./
              target: /var/www/html
        networks:
            sail:
            web:
            
networks:
    sail:
        driver: bridge
    web:
        name: proxy
        external: true  